import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
/**
 * ControlBar — barre de contrôle principale : analyser, jouer, stop, effacer,
 * sauvegarder, charger, exporter, importer, nouveau projet et extraction WAV.
 *
 * Design affiné (finesse des lignes, fonds sombres discrets, accents colorés
 * limités aux actions principales) — cohérent avec le mode Navig. Le tempo et
 * la bascule 📱 Navig. vivent dans la LiveSettingsBar (rangée de réglages).
 */
import { memo } from 'react';
import { Play, Square, Trash2, Save, FolderOpen, Download, FilePlus2 } from 'lucide-react';
/** Bouton neutre (fonds sombre, texte gris clair — style Navig). */
const btn = 'h-7 px-2.5 flex items-center gap-1.5 rounded-md text-[10px] font-semibold border transition-colors shrink-0 disabled:opacity-40 disabled:hover:bg-[#141a24]';
function ControlBar({ chords, playing, onAnalyse, onPlay, onStop, onClear, onSave, onLoad, onExport, onImport, onNewProject, onExtractWav, hasWav, }) {
    return (_jsx("div", { className: "bg-gray-900 rounded-xl border border-gray-800 p-2 sm:p-3 mb-2 overflow-x-auto", children: _jsxs("div", { className: "flex flex-wrap items-center gap-1.5 sm:gap-2 min-w-0", children: [_jsx("button", { onClick: onAnalyse, className: `${btn} bg-[#1a2230] border-[#2f4a6e] text-[#a8c8e8] hover:bg-[#22304a]`, title: "Analyser la grille saisie", children: "Analyser" }), _jsxs("button", { onClick: onPlay, disabled: playing || chords.length === 0, className: `${btn} bg-[#2f6ba8] border-[#3a7ab8] text-white hover:bg-[#3a7ab8] disabled:hover:bg-[#2f6ba8]`, children: [_jsx(Play, { className: "w-3 h-3" }), " Jouer"] }), _jsxs("button", { onClick: onStop, className: `${btn} bg-[#141a24] border-[#242c3a] text-[#e8a0b0] hover:bg-[#2a1a24]`, children: [_jsx(Square, { className: "w-3 h-3" }), " Stop"] }), _jsxs("button", { onClick: onExtractWav, disabled: !hasWav, className: `${btn} bg-[#141a24] border-[#242c3a] text-[#c9a45c] hover:bg-[#1a2230]`, title: "Extrait le dernier rendu WAV (mode Navig) en fichier .wav", children: [_jsx(Download, { className: "w-3 h-3" }), " Extract Wav"] }), _jsxs("button", { onClick: onClear, className: `${btn} bg-[#141a24] border-[#242c3a] text-[#9aa3b2] hover:text-white hover:bg-[#1a2230]`, title: "Effacer la grille", children: [_jsx(Trash2, { className: "w-3 h-3" }), " Effacer"] }), _jsx("div", { className: "w-px h-5 bg-[#242c3a] shrink-0" }), _jsxs("button", { onClick: onSave, className: `${btn} bg-[#141a24] border-[#242c3a] text-[#9aa3b2] hover:text-white hover:bg-[#1a2230]`, title: "Sauvegarder le projet", children: [_jsx(Save, { className: "w-3 h-3" }), " Save"] }), _jsxs("button", { onClick: onLoad, className: `${btn} bg-[#141a24] border-[#242c3a] text-[#9aa3b2] hover:text-white hover:bg-[#1a2230]`, title: "Charger un projet", children: [_jsx(FolderOpen, { className: "w-3 h-3" }), " Load"] }), _jsxs("button", { onClick: onNewProject, className: `${btn} bg-[#141a24] border-[#242c3a] text-[#9aa3b2] hover:text-white hover:bg-[#1a2230]`, title: "Nouveau projet \u2014 efface la grille, les pistes et les r\u00E9glages pour repartir de z\u00E9ro", children: [_jsx(FilePlus2, { className: "w-3 h-3" }), " Nouveau"] }), _jsx("button", { onClick: onExport, className: `${btn} bg-[#141a24] border-[#242c3a] text-[#9aa3b2] hover:text-white hover:bg-[#1a2230]`, title: "Exporter", children: "\uD83D\uDCE4" }), _jsx("button", { onClick: onImport, className: `${btn} bg-[#141a24] border-[#242c3a] text-[#9aa3b2] hover:text-white hover:bg-[#1a2230]`, title: "Importer", children: "\uD83D\uDCE5" })] }) }));
}
export default memo(ControlBar);
